name: flutting_workout
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
